on:
  push:
    branches:
      - master

jobs:
  update_leetcode_readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Update LeetCode README
    steps:
      - uses: actions/checkout@v3
      #Set up JDK 17 & Maven cache
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin'
            java-version: '17'
            cache: 'maven'
      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml,
          java SpringBootReadmeHelperApplication.java
